name: "Build and push"

on:
  push:
    branches:
      - "**"
      
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.alpine
          push: true
          tags: yuriikirychuk/gl-basecamp:latest-alpine
          no-cache: true
          platforms: linux/amd64
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}